import type { PrototypeState } from "./types";

export const initialPrototypeState: PrototypeState = {
  business: {
    id: "business-brightwash",
    name: "BrightWash Exterior Cleaning",
    shortName: "BrightWash",
    location: "Bristol and surrounding areas",
    tagline: "Driveways and patios cleaned professionally, without waiting for a site visit.",
    phone: "0117 555 0172",
    slug: "brightwash",
  },
  enquiries: [
    {
      id: "demo-001",
      reference: "BW-ENQ-0147",
      businessId: "business-brightwash",
      customer: "Sarah Mitchell",
      mobile: "07123 456789",
      email: "sarah.mitchell@example.com",
      initials: "SM",
      postcode: "BS7",
      submittedAt: "2026-05-26T10:14:00Z",
      jobType: "Block-paved driveway clean",
      size: "Medium — approximately two cars",
      condition: "Moss and weeds between blocks",
      access: "Front driveway access; outside tap available",
      addOns: ["Re-sanding"],
      photoCount: 3,
      photoFilenames: ["driveway-wide.jpg", "driveway-close-1.jpg", "driveway-close-2.jpg"],
      notes: "Would like this completed before visitors arrive next month.",
      status: "new",
      readiness: "One detail to confirm",
      missing: "Confirm approximate square metres or vehicle capacity before setting final scope.",
      summary:
        "Customer wants a block-paved driveway pressure washed, with moss removal and re-sanding. Three photos supplied. Access appears straightforward.",
    },
    {
      id: "demo-002",
      reference: "BW-ENQ-0146",
      businessId: "business-brightwash",
      customer: "Mark Lewis",
      mobile: "07987 654321",
      email: "mark.lewis@example.com",
      initials: "ML",
      postcode: "BS5",
      submittedAt: "2026-05-26T09:07:00Z",
      jobType: "Rear slab patio clean",
      size: "Small",
      condition: "Heavy algae staining",
      access: "Narrow side gate",
      addOns: [],
      photoCount: 4,
      photoFilenames: ["patio-1.jpg", "patio-2.jpg", "patio-3.jpg", "patio-4.jpg"],
      notes: "Dog in property; call before visiting.",
      status: "reviewing",
      readiness: "Ready for review",
      missing: "None indicated.",
      summary: "Small rear patio with algae staining and restricted access. Four photos supplied.",
    },
    {
      id: "demo-003",
      reference: "BW-ENQ-0145",
      businessId: "business-brightwash",
      customer: "Hannah Byrne",
      mobile: "07888 112233",
      email: "hannah.byrne@example.com",
      initials: "HB",
      postcode: "BS16",
      submittedAt: "2026-05-25T16:52:00Z",
      jobType: "Driveway clean and sealing",
      size: "Large / unsure",
      condition: "General weathering",
      access: "Driveway access",
      addOns: ["Protective sealing"],
      photoCount: 2,
      photoFilenames: ["driveway-before.jpg", "sealing-area.jpg"],
      notes: "Interested in a long-lasting finish.",
      status: "quote_draft",
      readiness: "Needs measurement",
      missing: "Measure surface area and confirm suitable sealing material.",
      summary: "Customer requests large driveway cleaning and sealing; area requires confirmation.",
    },
  ],
  quotes: [
    {
      id: "quote-demo-001",
      enquiryId: "demo-001",
      businessId: "business-brightwash",
      customer: "Sarah Mitchell",
      quoteNumber: "BW-2026-0042",
      issuedAt: "2026-05-25",
      validUntil: "2026-06-08",
      status: "accepted",
      items: [
        { id: "item-1", quoteId: "quote-demo-001", description: "Block-paving pressure wash", price: 18000 },
        { id: "item-2", quoteId: "quote-demo-001", description: "Moss and weed removal treatment", price: 3500 },
        { id: "item-3", quoteId: "quote-demo-001", description: "Re-sanding after cleaning", price: 7000 },
      ],
      total: 28500,
      deposit: 6000,
      balance: 22500,
      notes:
        "Includes surface clean, moss and weed treatment, and re-sanding after the surface has dried. Outside tap access required on the day.",
    },
  ],
  quoteAcceptances: [
    {
      id: "acceptance-1",
      quoteId: "quote-demo-001",
      acceptedAt: "2026-05-26T10:41:00Z",
      acceptedBy: "Sarah Mitchell",
      termsAcknowledged: true,
    },
  ],
  payments: [
    {
      id: "payment-1",
      quoteId: "quote-demo-001",
      amount: 6000,
      currency: "GBP",
      status: "succeeded",
      createdAt: "2026-05-26T10:43:00Z",
      updatedAt: "2026-05-26T10:43:00Z",
      reference: "DEMO-DEP-001",
    },
  ],
  auditEvents: [
    {
      id: "event-1",
      businessId: "business-brightwash",
      enquiryId: "demo-001",
      occurredAt: "2026-05-26T10:14:00Z",
      event: "New enquiry received",
      detail: "Customer uploaded 3 photos",
    },
    {
      id: "event-2",
      businessId: "business-brightwash",
      enquiryId: "demo-001",
      occurredAt: "2026-05-26T10:19:00Z",
      event: "Enquiry reviewed",
      detail: "Quote preparation started",
    },
    {
      id: "event-3",
      businessId: "business-brightwash",
      enquiryId: "demo-001",
      quoteId: "quote-demo-001",
      occurredAt: "2026-05-26T10:27:00Z",
      event: "Quote sent",
      detail: "BW-2026-0042 · £285",
    },
    {
      id: "event-4",
      businessId: "business-brightwash",
      enquiryId: "demo-001",
      quoteId: "quote-demo-001",
      occurredAt: "2026-05-26T10:41:00Z",
      event: "Customer accepted quote",
      detail: "Terms acknowledgement captured",
    },
    {
      id: "event-5",
      businessId: "business-brightwash",
      enquiryId: "demo-001",
      quoteId: "quote-demo-001",
      occurredAt: "2026-05-26T10:43:00Z",
      event: "Deposit received",
      detail: "£60 paid securely",
    },
  ],
};
